version: 2

sources:
- name: COVID_ALLIANCE
  database: JIRA4U
  schema: COVID_ALLIANCE
  tables:

  - name: c19_trk_us_states_current
    description: |
      [c19_trk_us_states_current](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_current.csv)
      - Repository: COVID19Tracking/covid-tracking-data
      - Folder: data
      - Search Endpoint: https://api.github.com/search/code?q=path:data+filename:state_current+extension:csv+repo:COVID19Tracking/covid-tracking-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/covid-tracking-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ daily updates (additional rows). Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse states_current content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_states_daily
    description: |
      [c19_trk_us_states_daily](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_daily_4pm_et.csv)
      - Repository: COVID19Tracking/covid-tracking-data
      - Folder: data
      - Search Endpoint: https://api.github.com/search/code?q=path:data+filename:states_daily_4pm_et+extension:csv+repo:COVID19Tracking/covid-tracking-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/covid-tracking-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ daily updates (updated rows). Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse states_daily content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_states_info
    description: |
      [c19_trk_us_states_info](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_info.csv)
      - Repository: COVID19Tracking/covid-tracking-data
      - Folder: data
      - Search Endpoint: https://api.github.com/search/code?q=path:data+filename:states_info+extension:csv+repo:COVID19Tracking/covid-tracking-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/covid-tracking-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ occasional updates (updated rows). Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, ecode, parse states_info content and convert to JSON, camelCase to snake_case field keys


  - name: c19_trk_us_population_states
    description: |
      [c19_trk_us_population_states](https://github.com/COVID19Tracking/associated-data/blob/master/us_census_data/us_census_2018_population_estimates_states.csv)
      - Repository: COVID19Tracking/associated-data
      - Folder: us_census_data
      - Search Endpoint: https://api.github.com/search/code?q=path:us_census_data+filename:us_census_2018_population_estimates_states+extension:csv+repo:COVID19Tracking/associated-data&sort=indexed&order=asc
          - Exclude: agegroups file
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/associated-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ minimal updates. Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove conte   tags: ["COVID 19 Tap"]nt node, add repository fields, decode, parse us_population_states content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_population_states_age_groups
    description: |
      [c19_trk_us_population_states_age_groups](https://github.com/COVID19Tracking/associated-data/blob/master/us_census_data/us_census_2018_population_estimates_states_agegroups.csv)
      - Repository: COVID19Tracking/associated-data
      - Folder: us_census_data
      - Search Endpoint: https://api.github.com/search/code?q=path:us_census_data+filename:us_census_2018_population_estimates_states_agegroups+extension:csv+repo:COVID19Tracking/associated-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/associated-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ minimal updates. Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us_population_states_age_groups content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_population_counties
    description: |
      [c19_trk_us_population_counties](https://github.com/COVID19Tracking/associated-data/blob/master/us_census_data/us_census_2018_population_estimates_counties.csv)
      - Repository: COVID19Tracking/associated-data
      - Folder: us_census_data
      - Search Endpoint: https://api.github.com/search/code?q=path:us_census_data+filename:us_census_2018_population_estimates_counties+extension:csv+repo:COVID19Tracking/associated-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/associated-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ minimal updates. Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us_population_counties content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_states_acs_health_insurance
    description: |
      [c19_trk_us_states_acs_health_insurance](https://github.com/COVID19Tracking/associated-data/blob/master/acs_health_insurance/acs_2018_health_insurance_coverage_estimates.csv)
      - Repository: COVID19Tracking/associated-data
      - Folder: acs_health_insurance
      - Search Endpoint: https://api.github.com/search/code?q=path:acs_health_insurance+filename:acs_2018_health_insurance_coverage_estimates+extension:csv+repo:COVID19Tracking/associated-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/associated-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ minimal updates. Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us_acs_health_insurance content and convert to JSON, camelCase to snake_case field keys

  - name: c19_trk_us_states_kff_hospital_beds
    description: |
      [c19_trk_us_states_kff_hospital_beds_files (per 1000 population)](https://github.com/COVID19Tracking/associated-data/blob/master/kff_hospital_beds/kff_usa_hospital_beds_per_capita_2018.csv)
      - Repository: COVID19Tracking/associated-data
      - Folder: kff_hospital_beds
      - Search Endpoint: https://api.github.com/search/code?q=path:kff_hospital_beds+filename:kff_usa_hospital_beds_per_capita_2018+extension:csv+repo:COVID19Tracking/associated-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/COVID19Tracking/associated-data/contents/[GIT_FILE_PATH]
      - Original Sourc: KFF (Kaiser Family Foundation)
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ minimal updates. Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us_kff_hospital_beds content and convert to JSON, camelCase to snake_case field keys


  - name: nytimes_us_states
    description: |
      [nytimes_us_states](https://github.com/nytimes/covid-19-data/blob/master/us-states.csv)
      - Repository: nytimes/covid-19-data
      - Folder: . (root folder)
      - Search Endpoint: https://api.github.com/search/code?q=filename:us-states+extension:csv+repo:nytimes/covid-19-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/nytimes/covid-19-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ daily updates (additional rows). Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us-states content and convert to JSON, lookup state_name

  - name: nytimes_us_counties
    description: |
      [nytimes_us_counties](https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv)
      - Repository: nytimes/covid-19-data
      - Folder: . (root folder)
      - Search Endpoint: https://api.github.com/search/code?q=filename:us-counties+extension:csv+repo:nytimes/covid-19-data&sort=indexed&order=asc
      - File Endpoint: https://api.github.com/repos/nytimes/covid-19-data/contents/[GIT_FILE_PATH]
      - Primary key fields: __sdc_row_number
      - Replication strategy: Single file w/ daily updates (additional rows). Use FULL_TABLE replication w/ activate_version.
        - Bookmark field: git_last_modified
      - Transformations: Remove content node, add repository fields, decode, parse us-counties content and convert to JSON, lookup state_name
