version: 2

sources:
- name: TAP_COVID_19
  tables:
  - name: C19_TRK_US_DAILY
  - name: C19_TRK_US_POPULATION_COUNTIES
  - name: C19_TRK_US_POPULATION_STATES
  - name: C19_TRK_US_POPULATION_STATES_AGE_GROUPS
  - name: C19_TRK_US_STATES_ACS_HEALTH_INSURANCE
  - name: C19_TRK_US_STATES_CURRENT
  - name: C19_TRK_US_STATES_DAILY
  - name: C19_TRK_US_STATES_INFO
  - name: C19_TRK_US_STATES_KFF_HOSPITAL_BEDS
  - name: NYTIMES_US_COUNTIES
  - name: NYTIMES_US_STATES